### ISSUE TITLE
在运行demo_cli.py时出错

### ISSUE THREAD

**Issue by 9527-567** [babysor/Realtime-Voice-Clone-Chinese#1]
我同时下载了原模型和你的模型，但是在运行demo_cli.py时出现以下错误：

RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([66, 512]) from checkpoint, the shape in current model is torch.Size([70, 512]).

**Comment by babysor** [comment]
> 我同时下载了原模型和你的模型，但是在运行demo_cli.py时出现以下错误：
> 
> RuntimeError: Error(s) in loading state_dict for Tacotron:
> size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([66, 512]) from checkpoint, the shape in current model is torch.Size([70, 512]).

demo_cli.py没有被完整测试，你有试过demo_toolbox吗？ 之前我遇到过这样的问题，都是pytorch版本不同导致的，临时解决方式如果只是应用模型，就用先用cpu

**Comment by 9527-567** [comment]
好的，我去试一试，十分感谢

**Comment by fyuvb** [comment]
遇到同样的问题，看了一下代码，应该是因为你没有配置用 mandarin.pt 做 synthesizer，还是用了 default 从 原来 model 下载的 synthesizer/saved_models/pretrained/pretrained.pt

Try this：
`python3 demo_cli.py --syn_model_fpath=synthesizer/saved_models/mandarin/mandarin.pt`

Dig 了一下问题，应该是，英文原版的 symbol list 是:
`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\'\"(),-.:;? ` 长度是 66

这个repo 的 symbol list是 
`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? ` 长度是 70.
所以在 Construct Tacotron 的时候会报 dimension not correct 的错误

**Comment by fanOfJava** [comment]
> 遇到同样的问题，看了一下代码，应该是因为你没有配置用 mandarin.pt 做 synthesizer，还是用了 default 从 原来 model 下载的 synthesizer/saved_models/pretrained/pretrained.pt
> 
> Try this：
> `python3 demo_cli.py --syn_model_fpath=synthesizer/saved_models/mandarin/mandarin.pt`
> 
> Dig 了一下问题，应该是，英文原版的 symbol list 是:
> `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\'\"(),-.:;? ` 长度是 66
> 
> 这个repo 的 symbol list是
> `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? ` 长度是 70.
> 所以在 Construct Tacotron 的时候会报 dimension not correct 的错误

最新公布的模型已经长度是75了，代码里的 `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? ` 长度是 70，两者又不匹配了。修改代码为 `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\'(),-.:;? ` ，程序可以跑通，但是合成的中文要么是纯噪音，要么就是质量很差，不知道是我哪里使用有问题：
使用如下：
python3 demo_cli.py --syn_model_fpath=synthesizer/saved_models/mandarin/mandarin.pt

**Comment by babysor** [comment]
> > 遇到同样的问题，看了一下代码，应该是因为你没有配置用 mandarin.pt 做 synthesizer，还是用了 default 从 原来 model 下载的 synthesizer/saved_models/pretrained/pretrained.pt
> > Try this：
> > `python3 demo_cli.py --syn_model_fpath=synthesizer/saved_models/mandarin/mandarin.pt`
> > Dig 了一下问题，应该是，英文原版的 symbol list 是:
> > `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\'\"(),-.:;? ` 长度是 66
> > 这个repo 的 symbol list是
> > `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? ` 长度是 70.
> > 所以在 Construct Tacotron 的时候会报 dimension not correct 的错误
> 
> 最新公布的模型已经长度是75了，代码里的 `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? ` 长度是 70，两者又不匹配了。修改代码为 `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\'(),-.:;? ` ，程序可以跑通，但是合成的中文要么是纯噪音，要么就是质量很差，不知道是我哪里使用有问题：
> 使用如下：
> python3 demo_cli.py --syn_model_fpath=synthesizer/saved_models/mandarin/mandarin.pt

可以加我微信看一下 1866198四 我猜是没有训练出来attention 线

**Comment by babysor** [comment]
> mandarin.pt



> > 遇到同样的问题，看了一下代码，应该是因为你没有配置用 mandarin.pt 做 synthesizer，还是用了 default 从 原来 model 下载的 synthesizer/saved_models/pretrained/pretrained.pt
> > Try this：
> > `python3 demo_cli.py --syn_model_fpath=synthesizer/saved_models/mandarin/mandarin.pt`
> > Dig 了一下问题，应该是，英文原版的 symbol list 是:
> > `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\'\"(),-.:;? ` 长度是 66
> > 这个repo 的 symbol list是
> > `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? ` 长度是 70.
> > 所以在 Construct Tacotron 的时候会报 dimension not correct 的错误
> 
> 最新公布的模型已经长度是75了，代码里的 `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? ` 长度是 70，两者又不匹配了。修改代码为 `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\'(),-.:;? ` ，程序可以跑通，但是合成的中文要么是纯噪音，要么就是质量很差，不知道是我哪里使用有问题：
> 使用如下：
> python3 demo_cli.py --syn_model_fpath=synthesizer/saved_models/mandarin/mandarin.pt

你train的mandarin.pt的记录plot里面最新的两个截图我看看？

**Comment by babysor** [comment]
隐藏未测试的demo_cli文件，关闭本issue

**Comment by fanOfJava** [comment]
> > mandarin.pt
> 
> > > 遇到同样的问题，看了一下代码，应该是因为你没有配置用 mandarin.pt 做 synthesizer，还是用了 default 从 原来 model 下载的 synthesizer/saved_models/pretrained/pretrained.pt
> > > Try this：
> > > `python3 demo_cli.py --syn_model_fpath=synthesizer/saved_models/mandarin/mandarin.pt`
> > > Dig 了一下问题，应该是，英文原版的 symbol list 是:
> > > `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\'\"(),-.:;? ` 长度是 66
> > > 这个repo 的 symbol list是
> > > `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? ` 长度是 70.
> > > 所以在 Construct Tacotron 的时候会报 dimension not correct 的错误
> > 
> > 
> > 最新公布的模型已经长度是75了，代码里的 `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? ` 长度是 70，两者又不匹配了。修改代码为 `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\'(),-.:;? ` ，程序可以跑通，但是合成的中文要么是纯噪音，要么就是质量很差，不知道是我哪里使用有问题：
> > 使用如下：
> > python3 demo_cli.py --syn_model_fpath=synthesizer/saved_models/mandarin/mandarin.pt
> 
> 你train的mandarin.pt的记录plot里面最新的两个截图我看看？

mandarin.pt就是你放在百度网盘上的模型

**Comment by JOJOda123** [comment]
有没有闪退呢，我之前启动GUI闪退了然后按照作者这个方法就可以了，链接：https://github.com/babysor/MockingBird/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF
