### ISSUE TITLE
关于训练和推理的疑问

### ISSUE THREAD

**Issue by PeijiYang** [babysor/Realtime-Voice-Clone-Chinese#11]
据我了解，datatang和slr68数据集都是针对ASR的数据，所以没有标注phoneme，那训练的时候是直接使用文字token还是先将文字转换成phoneme在进行训练。另外在您的演示视频中，我貌似看到是使用phoneme作为输入，如果是使用文字训练，inference的时候用phoneme，这之间又有什么样的处理。

**Comment by babysor** [comment]
可以看下code，用了pypinyin进行了phoneme转换。
演示视频那个时候只支持phoneme输入，现在有个github友今晚会提交支持中文输入

**Comment by PeijiYang** [comment]
> 可以看下code，用了pypinyin进行了phoneme转换。�
> 演示视频那个时候只支持phoneme输入，现在有个github友今晚会提交支持中文输入

也就是说训练的过程还是 phoneme -> mel -> wav的过程吧~

**Comment by babysor** [comment]
是的，
