### ISSUE TITLE
调用作者提供的预训练模型出错。

### ISSUE THREAD

**Issue by PeijiYang** [babysor/Realtime-Voice-Clone-Chinese#12]
![image](https://user-images.githubusercontent.com/17819608/129539162-f030a251-0c06-4eea-9335-778712b2b317.png)
encoder.embedding.weight不匹配的问题。

**Comment by babysor** [comment]
如果复用我的模型，需要把 `synthesizer\utils\symbols ` 里的
`_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? '`
改为
`_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\'(),-.:;? '`
因为是早期训练的模型，所以配置不太一样

**Comment by PeijiYang** [comment]
> 如果复用我的模型，需要把 `synthesizer\utils\symbols ` 里的
> `_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? '`
> 改为
> `_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\'(),-.:;? '`
> 因为是早期训练的模型，所以配置不太一样

1、如果自己训练的话，需要更改这块的配置吗？
2、在其他issue中看到按照这种方法修改后的效果好像不是很好，是否有计划提供别的pretrained model~

**Comment by babysor** [comment]
> > 如果复用我的模型，需要把 `synthesizer\utils\symbols ` 里的
> > `_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz12340!\'(),-.:;? '`
> > 改为
> > `_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!\'(),-.:;? '`
> > 因为是早期训练的模型，所以配置不太一样
> 
> 1、如果自己训练的话，需要更改这块的配置吗？
> 2、在其他issue中看到按照这种方法修改后的效果好像不是很好，是否有计划提供别的pretrained model~
别的model从0开始的话需要比较长的时间
之后测试新的数据集的时候，我再试试，训练好的话就提供
