### ISSUE TITLE
speaker encoder的输出向量是什么样的？

### ISSUE THREAD

**Issue by yileld** [babysor/Realtime-Voice-Clone-Chinese#15]
SVT2TTS的评论区过来的，自己训练的speaker encoder，因为用的aishell3数据集，214个说话人，而输出的speaker embedding是256维的，这就导致每个说话人的向量很稀疏，大部分维度是0，几乎是one-hot形式的。所以用来训练synthesizer的话根本训练不了，loss是Nan。
你这个模型训练synthesizer时有注意到speaker embedding向量大概是什么样的吗？

**Comment by babysor** [comment]
![image](https://user-images.githubusercontent.com/7423248/129876007-15671cca-6c77-4f7a-830e-2891256e74b0.png)
参考论文

**Comment by yileld** [comment]
> ![image](https://user-images.githubusercontent.com/7423248/129876007-15671cca-6c77-4f7a-830e-2891256e74b0.png)
> 参考论文

额。。我是指你得到的character embedding的数值是怎样的 ，不是问的结构和维度。

**Comment by babysor** [comment]
> > ![image](https://user-images.githubusercontent.com/7423248/129876007-15671cca-6c77-4f7a-830e-2891256e74b0.png)
> > 参考论文
> 
> 额。。我是指你得到的speaker embedding的数值是怎样的 ，不是问的结构和维度。

embedding我发一个截图给你，你跑的是aishell我记得不是我这个repo支持的吧？
![image](https://user-images.githubusercontent.com/7423248/129997160-3ddb0530-75e7-4716-a27d-96c30782271b.png)

**Comment by yileld** [comment]
> > > ![image](https://user-images.githubusercontent.com/7423248/129876007-15671cca-6c77-4f7a-830e-2891256e74b0.png)
> > > 参考论文
> > 
> > 
> > 额。。我是指你得到的speaker embedding的数值是怎样的 ，不是问的结构和维度。
> 
> embedding我发一个截图给你，你跑的是aishell我记得不是我这个repo支持的吧？
> ![image](https://user-images.githubusercontent.com/7423248/129997160-3ddb0530-75e7-4716-a27d-96c30782271b.png)

感谢！不过这是16进制不可读的形式的。。。你能不能np.load再print出来，麻烦了
