### ISSUE TITLE
关于该项目的一些想法。

### ISSUE THREAD

**Issue by PeijiYang** [babysor/Realtime-Voice-Clone-Chinese#16]
目前来看，该项目在实际使用的时候远达不到“可用”的程度。包括以下几种问题：
1、合成的音频会出现不包含正常人声，而是噪声和残缺的声音。
2、合成的音色跟目标音色不一致，差别很大。

目前分析出现问题一的原因应该是因为
1、asr数据中有些数据存在明显过强底噪，音频和文本或者音素数据无法对齐。（加入一些数据清洗的手段）
2、目前的d-vector和vocoder部分都是使用的英文数据集上训练的universal的版本，在中文数据集上使用肯定会出现mismatch的问题。（我理解d-vector和vocoder应该需要在中文数据集上重新训练以获得更好的结果）
3、数据集中音色过少，导致很难找到跟目标音色较为一致的”参考音色“用于生成。（混合多种asr和tts数据集，构建一个大型的数据集，以提高对目标音色的适配程度）。

这块我应该也会着手做一些工作以尝试改进模型，希望有机会和作者合作。

**Comment by babysor** [comment]
> 目前来看，该项目在实际使用的时候远达不到“可用”的程度。包括以下几种问题：
> 1、合成的音频会出现不包含正常人声，而是噪声和残缺的声音。
> 2、合成的音色跟目标音色不一致，差别很大。
> 
> 目前分析出现问题一的原因应该是因为
> 1、asr数据中有些数据存在明显过强底噪，音频和文本或者音素数据无法对齐。（加入一些数据清洗的手段）
> 2、目前的d-vector和vocoder部分都是使用的英文数据集上训练的universal的版本，在中文数据集上使用肯定会出现mismatch的问题。（我理解d-vector和vocoder应该需要在中文数据集上重新训练以获得更好的结果）
> 3、数据集中音色过少，导致很难找到跟目标音色较为一致的”参考音色“用于生成。（混合多种asr和tts数据集，构建一个大型的数据集，以提高对目标音色的适配程度）。
> 
> 这块我应该也会着手做一些工作以尝试改进模型，希望有机会和作者合作。

欢迎贡献，可以联系我邮箱，我这边尽量及时回复跟你建立联系。（广告太多，就不放微信号了）
