### ISSUE TITLE
關於 Train synthesizer 的問題，求指導 !

### ISSUE THREAD

**Issue by XiuChen-Liu** [babysor/Realtime-Voice-Clone-Chinese#21]
你好
我已經下載了aidatatang_200zh這個數據集，並且把 aidatatang_200zh\corpus\train 底下的檔案都解壓縮完畢
但是當我要開始執行 `python synthesizer_preprocess_audio.py D:\google download`(我把檔案放在 D:\google download 這個路徑下 )
卻發生以下狀況:
`D:\python_demo\Realtime-Voice-Clone-Chinese>python synthesizer_preprocess_audio.py D:\google download\
D:\python_demo\Realtime-Voice-Clone-Chinese\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
usage: synthesizer_preprocess_audio.py [-h] [-o OUT_DIR] [-n N_PROCESSES] [-s] [--hparams HPARAMS] [--no_trim] [--no_alignments]
                                       [--dataset DATASET]
                                       datasets_root
synthesizer_preprocess_audio.py: error: unrecognized arguments: download\`

請問我可以怎麼解決問題呢? 我有查看之前 issues 的討論並沒有發現有類似問題，以下是我想到可能有問題的地方，還請作者為我解答，謝謝！

1.我只有解壓縮 aidatatang_200zh\corpus\train 底下的檔案，是否其他資料夾下的檔案也要解壓縮?
2.是不是只需要將所有 wav 檔單獨拉出來放在 aidatatang_200zh\corpus\train 底下然後再執行`python synthesizer_preprocess_audio.py D:\google download` ?
3. 輸入的指令不對
4. wav 檔 與 txt 檔是不是要預先處理，而我沒有進行處理?

**Comment by babysor** [comment]
3。文件路径有空格 要么加双引号要么把文件夹名称空格去掉

**Comment by XiuChen-Liu** [comment]
> 3。文件路径有空格 要么加双引号要么把文件夹名称空格去掉

我按照你說的把空格去掉，不過又出現以下錯誤:
`D:\python_demo\Realtime-Voice-Clone-Chinese\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Traceback (most recent call last):
  File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 52, in <module>
    import webrtcvad
ModuleNotFoundError: No module named 'webrtcvad'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 54, in <module>
    raise ModuleNotFoundError("Package 'webrtcvad' not found. This package enables "
ModuleNotFoundError: Package 'webrtcvad' not found. This package enables noise removal and is recommended. Please install and try again. If installation fails, use --no_trim to disable this error message.`

請問有可能是發生什麼事情嗎?

**Comment by XiuChen-Liu** [comment]
> > 3。文件路径有空格 要么加双引号要么把文件夹名称空格去掉
> 
> 我按照你說的把空格去掉，不過又出現以下錯誤
> 
> `D:\python_demo\Realtime-Voice-Clone-Chinese\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
> warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
> Traceback (most recent call last):
> File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 52, in
> import webrtcvad
> ModuleNotFoundError: No module named 'webrtcvad'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 54, in
> raise ModuleNotFoundError("Package 'webrtcvad' not found. This package enables "
> ModuleNotFoundError: Package 'webrtcvad' not found. This package enables noise removal and is recommended. Please install and try again. If installation fails, use --no_trim to disable this error message.`
> 
> 請問有可能是發生什麼事情嗎?

**Comment by XiuChen-Liu** [comment]
> > 3。文件路径有空格 要么加双引号要么把文件夹名称空格去掉
> 
> 我按照你說的把空格去掉，不過又出現以下錯誤
> 
> `D:\python_demo\Realtime-Voice-Clone-Chinese\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
> warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
> Traceback (most recent call last):
> File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 52, in
> import webrtcvad
> ModuleNotFoundError: No module named 'webrtcvad'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 54, in
> raise ModuleNotFoundError("Package 'webrtcvad' not found. This package enables "
> ModuleNotFoundError: Package 'webrtcvad' not found. This package enables noise removal and is recommended. Please install and try again. If installation fails, use --no_trim to disable this error message.`
> 
> 請問有可能是發生什麼事情嗎?


這邊問題已經解決，其中 ` ModuleNotFoundError: No module named 'webrtcvad'` 這個錯誤只要用 `pip install webrtcvad` 就能解決

**Comment by XiuChen-Liu** [comment]
@babysor 另外我想詢問您，之前有在 #5 當中說到你是用 100% cpu 跑一小時，是因為無法用GPU版本嗎，我不太清楚在這邊詢問，還希望你回答，謝謝!

**Comment by babysor** [comment]
> @babysor 另外我想詢問您，之前有在 #5 當中說到你是用 100% cpu 跑一小時，是因為無法用GPU嗎(因為我目前也是 100% CPU運轉中)，我不太清楚在這邊詢問，有方法是用GPU跑嗎?

有部分处理是必须通过CPU的，所以其中有一段cpu 100%很正常，但如果很多处理都是100%，那可能有问题。

**Comment by babysor** [comment]
> > > 3。文件路径有空格 要么加双引号要么把文件夹名称空格去掉
> > 
> > 
> > 我按照你說的把空格去掉，不過又出現以下錯誤
> > `D:\python_demo\Realtime-Voice-Clone-Chinese\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
> > warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
> > Traceback (most recent call last):
> > File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 52, in
> > import webrtcvad
> > ModuleNotFoundError: No module named 'webrtcvad'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 54, in
> > raise ModuleNotFoundError("Package 'webrtcvad' not found. This package enables "
> > ModuleNotFoundError: Package 'webrtcvad' not found. This package enables noise removal and is recommended. Please install and try again. If installation fails, use --no_trim to disable this error message.`
> > 請問有可能是發生什麼事情嗎?
> 
> 這邊問題已經解決，其中 ` ModuleNotFoundError: No module named 'webrtcvad'` 這個錯誤只要用 `pip install webrtcvad` 就能解決，之後如遇到 `分頁不足` 可以參考 #5 其中有人提到把內存改為100G就可以

你可以提个quick change到readme嘛

**Comment by XiuChen-Liu** [comment]
> > > > 3。文件路径有空格 要么加双引号要么把文件夹名称空格去掉
> > > 
> > > 
> > > 我按照你說的把空格去掉，不過又出現以下錯誤
> > > `D:\python_demo\Realtime-Voice-Clone-Chinese\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.") Traceback (most recent call last): File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 52, in import webrtcvad ModuleNotFoundError: No module named 'webrtcvad' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 54, in raise ModuleNotFoundError("Package 'webrtcvad' not found. This package enables " ModuleNotFoundError: Package 'webrtcvad' not found. This package enables noise removal and is recommended. Please install and try again. If installation fails, use --no_trim to disable this error message.`
> > > 請問有可能是發生什麼事情嗎?
> > 
> > 
> > 這邊問題已經解決，其中 ` ModuleNotFoundError: No module named 'webrtcvad'` 這個錯誤只要用 `pip install webrtcvad` 就能解決，之後如遇到 `分頁不足` 可以參考 #5 其中有人提到把內存改為100G就可以
> 
> 你可以提个quick change到readme嘛

不好意思，我是 github 的新手，我非常樂意提供我遇到難題的解決方法，不過要怎麼提到 readme 裡面讓遇到困難的人可以直接看到呢?

**Comment by XiuChen-Liu** [comment]
> > @babysor 另外我想詢問您，之前有在 #5 當中說到你是用 100% cpu 跑一小時，是因為無法用GPU嗎(因為我目前也是 100% CPU運轉中)，我不太清楚在這邊詢問，有方法是用GPU跑嗎?
> 
> 有部分处理是必须通过CPU的，所以其中有一段cpu 100%很正常，但如果很多处理都是100%，那可能有问题。

了解，謝謝!

**Comment by babysor** [comment]
> > > > > 3。文件路径有空格 要么加双引号要么把文件夹名称空格去掉
> > > > 
> > > > 
> > > > 我按照你說的把空格去掉，不過又出現以下錯誤
> > > > `D:\python_demo\Realtime-Voice-Clone-Chinese\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.") Traceback (most recent call last): File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 52, in import webrtcvad ModuleNotFoundError: No module named 'webrtcvad' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 54, in raise ModuleNotFoundError("Package 'webrtcvad' not found. This package enables " ModuleNotFoundError: Package 'webrtcvad' not found. This package enables noise removal and is recommended. Please install and try again. If installation fails, use --no_trim to disable this error message.`
> > > > 請問有可能是發生什麼事情嗎?
> > > 
> > > 
> > > 這邊問題已經解決，其中 ` ModuleNotFoundError: No module named 'webrtcvad'` 這個錯誤只要用 `pip install webrtcvad` 就能解決，之後如遇到 `分頁不足` 可以參考 #5 其中有人提到把內存改為100G就可以
> > 
> > 
> > 你可以提个quick change到readme嘛
> 
> 不好意思，我是 github 的新手，我非常樂意提供我遇到難題的解決方法，不過要怎麼提到 readme 裡面讓遇到困難的人可以直接看到呢?

你需要folk，修改之后提交git，申请pull request就好

**Comment by XiuChen-Liu** [comment]
> > > > > > 3。文件路径有空格 要么加双引号要么把文件夹名称空格去掉
> > > > > 
> > > > > 
> > > > > 我按照你說的把空格去掉，不過又出現以下錯誤
> > > > > `D:\python_demo\Realtime-Voice-Clone-Chinese\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.") Traceback (most recent call last): File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 52, in import webrtcvad ModuleNotFoundError: No module named 'webrtcvad' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 54, in raise ModuleNotFoundError("Package 'webrtcvad' not found. This package enables " ModuleNotFoundError: Package 'webrtcvad' not found. This package enables noise removal and is recommended. Please install and try again. If installation fails, use --no_trim to disable this error message.`
> > > > > 請問有可能是發生什麼事情嗎?
> > > > 
> > > > 
> > > > 這邊問題已經解決，其中 ` ModuleNotFoundError: No module named 'webrtcvad'` 這個錯誤只要用 `pip install webrtcvad` 就能解決，之後如遇到 `分頁不足` 可以參考 #5 其中有人提到把內存改為100G就可以
> > > 
> > > 
> > > 你可以提个quick change到readme嘛
> > 
> > 
> > 不好意思，我是 github 的新手，我非常樂意提供我遇到難題的解決方法，不過要怎麼提到 readme 裡面讓遇到困難的人可以直接看到呢?
> 
> 你需要folk，修改之后提交git，申请pull request就好

我花了一點時間研究，已經申請pull request了，再請作者看一下

**Comment by babysor** [comment]
> > > > > > > 3。文件路径有空格 要么加双引号要么把文件夹名称空格去掉
> > > > > > 
> > > > > > 
> > > > > > 我按照你說的把空格去掉，不過又出現以下錯誤
> > > > > > `D:\python_demo\Realtime-Voice-Clone-Chinese\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.") Traceback (most recent call last): File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 52, in import webrtcvad ModuleNotFoundError: No module named 'webrtcvad' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "D:\python_demo\Realtime-Voice-Clone-Chinese\synthesizer_preprocess_audio.py", line 54, in raise ModuleNotFoundError("Package 'webrtcvad' not found. This package enables " ModuleNotFoundError: Package 'webrtcvad' not found. This package enables noise removal and is recommended. Please install and try again. If installation fails, use --no_trim to disable this error message.`
> > > > > > 請問有可能是發生什麼事情嗎?
> > > > > 
> > > > > 
> > > > > 這邊問題已經解決，其中 ` ModuleNotFoundError: No module named 'webrtcvad'` 這個錯誤只要用 `pip install webrtcvad` 就能解決，之後如遇到 `分頁不足` 可以參考 #5 其中有人提到把內存改為100G就可以
> > > > 
> > > > 
> > > > 你可以提个quick change到readme嘛
> > > 
> > > 
> > > 不好意思，我是 github 的新手，我非常樂意提供我遇到難題的解決方法，不過要怎麼提到 readme 裡面讓遇到困難的人可以直接看到呢?
> > 
> > 
> > 你需要folk，修改之后提交git，申请pull request就好
> 
> 我花了一點時間研究，已經申請pull request了，再請作者看一下

通过了 不过这个好像是另一个修改？

**Comment by XiuChen-Liu** [comment]
什麼意思?

**Comment by XiuChen-Liu** [comment]
> 什麼意思?

我好像懂了 我再去研究一下
