### ISSUE TITLE
使用百度云上的模型，训练播放后都是杂音

### ISSUE THREAD

**Issue by non-one** [babysor/Realtime-Voice-Clone-Chinese#24]
#### 环境
Windows 10
Python 3.7

#### 描述
百度云的pt模型放入`synthesizer/saved_models/`后，`python .\demo_toolbox.py`可执行，但产生结果都是杂音，中文和拼音都不太行

#### 问题截图
![image](https://user-images.githubusercontent.com/32992657/130172771-ea760f6c-56ba-4672-9dea-62d4d4a9fa33.png)
![image](https://user-images.githubusercontent.com/32992657/130172858-a2183819-75fb-410c-b9c0-33e9e676121b.png)

本人纯小白，希望大佬有空给予指点。

**Comment by zhuzaileiting** [comment]
这一步有问题吗
C:\Users\Administrator\Desktop\Realtime-Voice-Clone-Chinese-main\Realtime-Voice-Clone-Chinese-main>python synthesizer_preprocess_audio.py E:\data\aidatatang_200zh
Arguments:
    datasets_root:   E:\data\aidatatang_200zh
    out_dir:         E:\data\aidatatang_200zh\SV2TTS\synthesizer
    n_processes:     None
    skip_existing:   False
    hparams:
    no_alignments:   False
    dataset:         aidatatang_200zh

Using data from:
    E:\data\aidatatang_200zh\aidatatang_200zh\corpus\train
aidatatang_200zh:  62%|█████████████████████████████████████████████████████████████████████████████▉                                               | 524/840 [46:39<29:46,  5.65s/speakers]

**Comment by non-one** [comment]
> 这一步有问题吗
> C:\Users\Administrator\Desktop\Realtime-Voice-Clone-Chinese-main\Realtime-Voice-Clone-Chinese-main>python synthesizer_preprocess_audio.py E:\data\aidatatang_200zh
> Arguments:
> datasets_root: E:\data\aidatatang_200zh
> out_dir: E:\data\aidatatang_200zh\SV2TTS\synthesizer
> n_processes: None
> skip_existing: False
> hparams:
> no_alignments: False
> dataset: aidatatang_200zh
> 
> Using data from:
> E:\data\aidatatang_200zh\aidatatang_200zh\corpus\train
> aidatatang_200zh: 62%|█████████████████████████████████████████████████████████████████████████████▉ | 524/840 [46:39<29:46, 5.65s/speakers]

没有，我是直接拿pt放入目录下，没有执行这些命令

**Comment by zhuzaileiting** [comment]
数据集得加载，下载数据集   http://www.openslr.org/62/

**Comment by zhuzaileiting** [comment]
通过这些数据集（声音样本）与自己的（目标）样本学习后才能模仿声音

**Comment by non-one** [comment]
pt文件的作用是什么呢，怎么使用？
![image](https://user-images.githubusercontent.com/32992657/130175465-38c45321-acb7-42d0-9c00-b224c69a43a2.png)
按我个人理解，训练步骤的产出是模型文件

**Comment by zhuzaileiting** [comment]
@楼主解释一下

**Comment by non-one** [comment]
![image](https://user-images.githubusercontent.com/32992657/130175738-c88ccbf6-0b2a-414c-beb4-ca0b0a993a90.png)
作者是提供训练后的模型链接的，我显卡不够训练的，所以是直接拿来用的

**Comment by zhuzaileiting** [comment]
数据集是实体的声音文件样本，训练模型是分析中文优化吧

**Comment by non-one** [comment]
好吧，我还以为可以直接使用

**Comment by babysor** [comment]
> #### 环境
> Windows 10
> Python 3.7
> 
> #### 描述
> 百度云的pt模型放入`synthesizer/saved_models/`后，`python .\demo_toolbox.py`可执行，但产生结果都是杂音，中文和拼音都不太行
> 
> #### 问题截图
> ![image](https://user-images.githubusercontent.com/32992657/130172771-ea760f6c-56ba-4672-9dea-62d4d4a9fa33.png)
> ![image](https://user-images.githubusercontent.com/32992657/130172858-a2183819-75fb-410c-b9c0-33e9e676121b.png)
> 
> 本人纯小白，希望大佬有空给予指点。

最新代码的话是可以输入中文的,你用pinyin试过吗?
另外我看了一下图,你的录音输入好像也不太清晰,尽可能在5秒内说清晰2~3句话

**Comment by non-one** [comment]
按照B站上演示的视频，我进行了以下尝试：
- 更换拾音设备。原视频的输入图长得也差不多，应该不是主要原因
- 更换拼音形式。完全按照视频输入框内容，依然都是滋滋声
我考虑是直接使用模型的姿势不对，所以有使用百度云上模型文件成功的，请分享下经验，几天后issue我会关闭

**Comment by babysor** [comment]
> 按照B站上演示的视频，我进行了以下尝试：
> 
> * 更换拾音设备。原视频的输入图长得也差不多，应该不是主要原因
> * 更换拼音形式。完全按照视频输入框内容，依然都是滋滋声
>   我考虑是直接使用模型的姿势不对，所以有使用百度云上模型文件成功的，请分享下经验，几天后issue我会关闭

貌似找到问题了，图中你应该选择了英文版的synthesizer了，要在`synthesizer`一项中改为我上传的
![image](https://user-images.githubusercontent.com/7423248/130307432-950824f7-294d-4faa-9350-522455a58ae7.png)

**Comment by non-one** [comment]
这只是我参照原项目修改的文件名，改回原名也一样，很抱歉没说清楚。另外作者你方便出一版如何快速搭建demo的教程吗，让更多人可以直接上手，先不用考虑训练问题

**Comment by babysor** [comment]
> 这只是我参照原项目修改的文件名，改回原名也一样，很抱歉没说清楚。另外作者你方便出一版如何快速搭建demo的教程吗，让更多人可以直接上手，先不用考虑训练问题

目前会逐步优化，不过有蛮多朋友已经跑通了，这里可能有哪步出错了

**Comment by Larryvrh** [comment]
![Issue](https://user-images.githubusercontent.com/15991834/130313465-13ef4d81-29e5-4ead-9f14-be729c7caa56.png)
遇到了情况类似的问题，似乎是因为模型尺寸不匹配

**Comment by non-one** [comment]
> ![Issue](https://user-images.githubusercontent.com/15991834/130313465-13ef4d81-29e5-4ead-9f14-be729c7caa56.png)
> 遇到了情况类似的问题，似乎是因为模型尺寸不匹配

这个是输入框的问题，我也碰到过，对于某些中文或者字符不能很好识别，更换为其他短句试试

**Comment by wanghaisheng** [comment]
> 
> 
> 按照B站上演示的视频，我进行了以下尝试：
> 
>     * 更换拾音设备。原视频的输入图长得也差不多，应该不是主要原因
> 
>     * 更换拼音形式。完全按照视频输入框内容，依然都是滋滋声
>       我考虑是直接使用模型的姿势不对，所以有使用百度云上模型文件成功的，请分享下经验，几天后issue我会关闭

我想请教下 这个录音可以用现成的mp3文件吗

**Comment by babysor** [comment]
> > 按照B站上演示的视频，我进行了以下尝试：
> > ```
> > * 更换拾音设备。原视频的输入图长得也差不多，应该不是主要原因
> > 
> > * 更换拼音形式。完全按照视频输入框内容，依然都是滋滋声
> >   我考虑是直接使用模型的姿势不对，所以有使用百度云上模型文件成功的，请分享下经验，几天后issue我会关闭
> > ```
> 
> 我想请教下 这个录音可以用现成的mp3文件吗

可以的.

> > ![Issue](https://user-images.githubusercontent.com/15991834/130313465-13ef4d81-29e5-4ead-9f14-be729c7caa56.png)
> > 遇到了情况类似的问题，似乎是因为模型尺寸不匹配
> 
> 这个是输入框的问题，我也碰到过，对于某些中文或者字符不能很好识别，更换为其他短句试试

已经定位到问题,有个朋友正在修复中,你也可以看下,应该是synthesizer里面切割句子除了点问题

**Comment by usagiring** [comment]
我也是使用百度云上的模型，同样是杂音。
![11](https://user-images.githubusercontent.com/6501524/130348481-ad06fe65-710e-453c-a7cd-982c4502b442.jpg)

---
我自己训练了33k，能出类似声线，但还是杂音，是训练没到位吗？
![attention_step_33000_sample_1](https://user-images.githubusercontent.com/6501524/130348534-b2376c68-e1a1-4d2e-b93b-8ae9c7b698d5.png)
![step-33000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/6501524/130348536-2189d450-0046-4d79-83f6-9d15288c73fe.png)

**Comment by miven** [comment]
LOSS太高了 训练到0.4以下试试
分享下我训练的模型和效果：
链接：https://pan.baidu.com/s/1PI-hM3sn5wbeChRryX-RCQ 
提取码：2021 
训练效果视频
https://www.bilibili.com/video/BV1uh411B7AD/

**Comment by usagiring** [comment]
> LOSS太高了 训练到0.4以下试试
> 分享下我训练的模型和效果：
> 链接：https://pan.baidu.com/s/1PI-hM3sn5wbeChRryX-RCQ
> 提取码：2021
> 训练效果视频
> https://www.bilibili.com/video/BV1uh411B7AD/


这个模型可以的！

**Comment by babysor** [comment]
> LOSS太高了 训练到0.4以下试试
> 分享下我训练的模型和效果：
> 链接：https://pan.baidu.com/s/1PI-hM3sn5wbeChRryX-RCQ
> 提取码：2021
> 训练效果视频
> https://www.bilibili.com/video/BV1uh411B7AD/

方便分享到readme吗？你可以直接提 路过留痕一下commit 😄

**Comment by miven** [comment]
> 
> 
> > LOSS太高了 训练到0.4以下试试
> > 分享下我训练的模型和效果：
> > 链接：https://pan.baidu.com/s/1PI-hM3sn5wbeChRryX-RCQ
> > 提取码：2021
> > 训练效果视频
> > https://www.bilibili.com/video/BV1uh411B7AD/
> 
> 方便分享到readme吗？你可以直接提 路过留痕一下commit 😄

可以啊，方便大家测试，您可以直接加到readme中😄

**Comment by non-one** [comment]
> LOSS太高了 训练到0.4以下试试
> 分享下我训练的模型和效果：
> 链接：https://pan.baidu.com/s/1PI-hM3sn5wbeChRryX-RCQ
> 提取码：2021
> 训练效果视频
> https://www.bilibili.com/video/BV1uh411B7AD/

谢谢大佬给的模型，demo可以跑通了，该issue得到解决，将关闭

**Comment by babysor** [comment]
> > > LOSS太高了 训练到0.4以下试试
> > > 分享下我训练的模型和效果：
> > > 链接：https://pan.baidu.com/s/1PI-hM3sn5wbeChRryX-RCQ
> > > 提取码：2021
> > > 训练效果视频
> > > https://www.bilibili.com/video/BV1uh411B7AD/
> > 
> > 
> > 方便分享到readme吗？你可以直接提 路过留痕一下commit 😄
> 
> 可以啊，方便大家测试，您可以直接加到readme中😄
提交啦还顺便@你了哈

**Comment by 576272658** [comment]
我也使用的miven大佬提供的模型，但是和你一样的问题，出来是杂音不知道是什么原因，加载encoder也很慢

**Comment by zhenqicai** [comment]
> #### 环境
> Windows 8.1 Python 3.7.9
> 
> #### 描述
> 你好，运行  demo_toolbox.py  出现以下错误是什么原因呢？
> 
> #### 问题截图
> ![image](https://user-images.githubusercontent.com/20643420/145243330-33fe80a1-4224-432b-bdb2-ea66ebb38ced.png)
> ![image](https://user-images.githubusercontent.com/20643420/145243486-022b614b-f7f8-405f-a278-ecf6f9412dab.png)
> ![image](https://user-images.githubusercontent.com/20643420/145243611-fe0e99f7-147e-496f-a521-eef113c67f4d.png)
