### ISSUE TITLE
LibriSpeech alignments?

### ISSUE THREAD

**Issue by iloveflag** [babysor/Realtime-Voice-Clone-Chinese#26]
(base) F:\Realtime-Voice-Clone-Chinese-main>python synthesizer_preprocess_audio.py "F:\Realtime-Voice-Clone-Chinese-main/data1"
Arguments:
    datasets_root:   F:\Realtime-Voice-Clone-Chinese-main\data1
    out_dir:         F:\Realtime-Voice-Clone-Chinese-main\data1\SV2TTS\synthesizer
    n_processes:     None
    skip_existing:   False
    hparams:
    no_alignments:   False
    dataset:         aidatatang_200zh

Using data from:
    F:\Realtime-Voice-Clone-Chinese-main\data1\aidatatang_200zh\corpus\train
aidatatang_200zh: 100%|████████████████████████████████████████████████████████| 420/420 [02:47<00:00,  2.51speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 64, in <module>
    preprocess_dataset(**vars(args))
  File "F:\Realtime-Voice-Clone-Chinese-main\synthesizer\preprocess.py", line 76, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence
![image](https://user-images.githubusercontent.com/25424842/130206824-0250d241-b561-4d4a-9564-b0240f93fa98.png)

在此处发现同样问题:[https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/486](url)

**Comment by wangkewk** [comment]
我也一样，who  can     solve

**Comment by wangkewk** [comment]
解决方法；不要吧，文件里的所有wav格式的音频，剪切放在train文件夹，不要放在train文件夹

**Comment by wangkewk** [comment]
![image](https://user-images.githubusercontent.com/31000405/130222864-2d72e5da-56fb-4426-811d-28f3b9e592dc.png)

**Comment by wangkewk** [comment]
上图正确

**Comment by iloveflag** [comment]
![image](https://user-images.githubusercontent.com/25424842/130230148-e54d67fd-3a7a-47b7-b778-2b80610bfa29.png)
你的意思是解压所有压缩包吗？

**Comment by iloveflag** [comment]
> ![image](https://user-images.githubusercontent.com/25424842/130230148-e54d67fd-3a7a-47b7-b778-2b80610bfa29.png)
> 你的意思是解压所有压缩包吗？

解压train目录下的压缩包可解决

**Comment by wangkewk** [comment]
对，别让 wav移出来
