### ISSUE TITLE
使用预训练模型获得了奇怪的mel spectrogram和杂音

### ISSUE THREAD

**Issue by wfjsw** [babysor/Realtime-Voice-Clone-Chinese#31]
![image](https://user-images.githubusercontent.com/2220320/130367343-3bbe4b9c-57d0-4961-b266-4f2c3d5840cc.png)
voicepart1.mp3 是一段时长为10秒钟、含7个句子的录音片段
![image](https://user-images.githubusercontent.com/2220320/130367391-c45cff12-3bf3-4b92-b144-451ec60eb244.png)
voicepart2.wav 是一段时长为5秒钟的类似片段

合成结果均为约2秒的背景杂音，无论输入内容长度。
![image](https://user-images.githubusercontent.com/2220320/130367425-ea6c0590-fb67-4a06-b0f7-985b7bcd6bbd.png)

**Comment by wfjsw** [comment]
![image](https://user-images.githubusercontent.com/2220320/130367540-c118e0c4-fe4b-4403-ac46-1087ff75b299.png)
加了一个log之后长度变了 但声音还是杂音

**Comment by cronfox** [comment]
你是不是没有加载数据集?

**Comment by babysor** [comment]
> ~你是不是没有加载数据集?~
> 草 是不是因为修bug导致了新bug
> 我加载了以前训练的一个模型
> `size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([70, 512]) from checkpoint, the shape in current model is torch.Size([75, 512]).`

哈 最新commit里面symbols的文件可以考虑回滚一下，这个会破坏训练模型的兼容的

**Comment by wfjsw** [comment]
这个东西怎么说呢，多点点这个毛病就没有了所以我就没太在意它。让我看看

**Comment by wfjsw** [comment]
嗯，好了50%
用ceshi来做可以成功，但有时候还是杂音
用mandarin就基本还是issue里这个情况

**Comment by wfjsw** [comment]
emm这么说也不对，换了点东西，现在ceshi的成功率还是挺高的，但是mandarin出现了空句子的问题，大概跟预期结果比较相似了。
