### ISSUE TITLE
关于aidatatang_200zh的问题

### ISSUE THREAD

**Issue by 9527-567** [babysor/Realtime-Voice-Clone-Chinese#4]
我尝试从aidatatang_200zh的官网上下载，是要把aidatatang_200zh\aidatatang_200zh\aidatatang_200zh\corpus\train下的文件全部解压吗？

**Comment by babysor** [comment]
是的，建议路径不要这么深，到时候需要拼一下。这里的解压可以用bash的pipeline: `cat *.tar.gz | tar zxvf - -i`

**Comment by Evilran** [comment]
指定 datasets 所在的根路径就行了，也可以用这个pipeline：`ls *.tar.gz | xargs -n1 tar xzvf`
