### ISSUE TITLE
使用百度网盘最新预训练模型，spectrogram不正常，只有两秒杂音

### ISSUE THREAD

**Issue by gebumc** [babysor/Realtime-Voice-Clone-Chinese#42]
![image](https://user-images.githubusercontent.com/61355888/130432009-ca953fc9-5319-4bc0-b127-ec38fc060432.png)

**Comment by FuryMartin** [comment]
我刚才同样遇到了杂音问题，你可以试试参考#37 中的解决方法

**Comment by gebumc** [comment]
> 我刚才同样遇到了杂音问题，你可以试试参考#37 中的解决方法

谢谢！已经解决
