### ISSUE TITLE
bilibili 演示视频已消失

### ISSUE THREAD

**Issue by BackMountainDevil** [babysor/Realtime-Voice-Clone-Chinese#43]
[Bilibili](https://www.bilibili.com/video/BV1uh411B7AD/)

**Comment by miven** [comment]
演示视频已B站下架....
@babysor

**Comment by babysor** [comment]
> 演示视频已B站下架....
> @babysor

被警告了吗

**Comment by miven** [comment]
![QQ截图20210823224931](https://user-images.githubusercontent.com/12205188/130468230-ecebbb87-a286-47eb-ab23-9b19be2a1256.jpg)

莫名其妙的原因:
已退回 考虑到前台封面的展示，黑屏，边框，角标等情况，建议进行更换 查阅 哔哩哔哩创作公约 了解更多

**Comment by allwaysLove** [comment]
@babysor 可以将视频重新发布一下嘛。或者上传到github或者百度云

**Comment by mgxhl** [comment]
> ![QQ截图20210823224931](https://user-images.githubusercontent.com/12205188/130468230-ecebbb87-a286-47eb-ab23-9b19be2a1256.jpg)
> 
> 莫名其妙的原因:
> 已退回 考虑到前台封面的展示，黑屏，边框，角标等情况，建议进行更换 查阅 哔哩哔哩创作公约 了解更多

很常见的，就是封面不符合规范。换一个封面即可再提交，最简单的单色背景加文字都行，注意别撞色（大红大紫）。实在不会必剪上做个封面也成。毕竟这视频昨天还是系统推给我的，有系统推荐流量的，刚在pad上看了，上电脑就肥肠抱歉了。顺便说一句，站内那两条私信可以忽略了。

**Comment by miven** [comment]
> 
> 
> > ![QQ截图20210823224931](https://user-images.githubusercontent.com/12205188/130468230-ecebbb87-a286-47eb-ab23-9b19be2a1256.jpg)
> > 莫名其妙的原因:
> > 已退回 考虑到前台封面的展示，黑屏，边框，角标等情况，建议进行更换 查阅 哔哩哔哩创作公约 了解更多
> 
> 很常见的，就是封面不符合规范。换一个封面即可再提交，最简单的单色背景加文字都行，注意别撞色（大红大紫）。实在不会必剪上做个封面也成。毕竟这视频昨天还是系统推给我的，有系统推荐流量的，刚在pad上看了，上电脑就肥肠抱歉了。顺便说一句，站内那两条私信可以忽略了。

谢谢老哥，经过修改，视频已经通过。
