### ISSUE TITLE
如何解决运行python synthesizer_preprocess_audio.py时报错 DLL load failed:页面文件太小，无法完成操作

### ISSUE THREAD

**Issue by 9527-567** [babysor/Realtime-Voice-Clone-Chinese#5]
我在运行 python synthesizer_preprocess_audio.py时遇到如上错误 ，在CSDN上找到解决方法：1.如果python 运行环境不在C盘  查看高级系统设置->高级->性能 设置->高级->虚拟内存->更改 ->取消自动管理所有驱动器的分页文件大小-> 自定义大小 ->初始大小和最大值设为10240    2. 更改DateLoade 中的参数num_worker 改为0 但我现在不清楚具体怎样把参数设为0

**Comment by miven** [comment]
是不是python版本的问题，本机python3.7 和colab没有出现这个问题

**Comment by 9527-567** [comment]
> 是不是python版本的问题，本机python3.7 和colab没有出现这个问题
我用的是  python 3.8.5

**Comment by miven** [comment]
> 
> 
> > 是不是python版本的问题，本机python3.7 和colab没有出现这个问题
> > 我用的是  python 3.8.5

那你换3.7试试 我用的anaconda

**Comment by babysor** [comment]
试过查看机器上是否有过多的python进程吗》

**Comment by DreamFlyer-Lab** [comment]
虚拟内存改成100G就好了

**Comment by thisjam** [comment]
新笔记本电脑5800h  Cpu%2使用  运行python synthesizer_preprocess_audio.py直接到100% 
裂开

**Comment by babysor** [comment]
> 新笔记本电脑5800h Cpu%2使用 运行python synthesizer_preprocess_audio.py直接到100%
> 裂开

兄弟我也笔记本，只能跑小数据集

**Comment by thisjam** [comment]
> > 新笔记本电脑5800h Cpu%2使用 运行python synthesizer_preprocess_audio.py直接到100%
> > 裂开
> 
> 兄弟我也笔记本，只能跑小数据集
项目启不起来，你给的模型不能用，，看你视频也是选了两个模型啊，你只传了一个。
不知道是哪里没弄好，跑不起来
自己运行python synthesizer_preprocess_audio.py 电脑就炸

**Comment by babysor** [comment]
> > > 新笔记本电脑5800h Cpu%2使用 运行python synthesizer_preprocess_audio.py直接到100%
> > > 裂开
> > 
> > 
> > 兄弟我也笔记本，只能跑小数据集
> > 项目启不起来，你给的模型不能用，，看你视频也是选了两个模型啊，你只传了一个。
> > 不知道是哪里没弄好，跑不起来
> > 自己运行python synthesizer_preprocess_audio.py 电脑就炸

我是cpu 100%跑一小时预热

**Comment by thisjam** [comment]
> 我是cpu 100%跑一小时预热

我是加载数据集处理的时候就炸了，根本到不了训练的那里
感觉aidatatang这个数据集质量不太行啊 全是噪音，有些人的话也说不清楚
自己找了个很小的数据集，不知道会不会卡，因为不会处理数据 0.0
能说说处理数据的原理吗

**Comment by babysor** [comment]
> > 我是cpu 100%跑一小时预热
> 
> 我是加载数据集处理的时候就炸了，根本到不了训练的那里
> 感觉aidatatang这个数据集质量不太行啊 全是噪音，有些人的话也说不清楚
> 自己找了个很小的数据集，不知道会不会卡，因为不会处理数据 0.0
> 能说说处理数据的原理吗
看这一段 https://github.com/babysor/Realtime-Voice-Clone-Chinese/blob/main/synthesizer/preprocess.py#L42-L60
不同数据集只需要关心这段里面的 中文字幕转 phoneme -> mel, 其他就是把phoneme和音频文件对应起来
可以加一下我wechat一起沟通一下，1866198四 补充一个新数据集
