### ISSUE TITLE
这个项目需要自己训练吗？

### ISSUE THREAD

**Issue by thisjam** [babysor/Realtime-Voice-Clone-Chinese#9]
Pretrained-models下了放根目录不行  拷贝了到相对应的文件目录才能启动工具箱
只能load数据集的语音
无法使用解析功能
说明不详细不会用啊
出一个详细的步骤文档吧

**Comment by babysor** [comment]
不着急，这个确实要自己的训练的。你已经成功迈出第一步，你可以把这一步替换的步骤细化直接在项目修改 成为项目贡献者 感谢

**Comment by thisjam** [comment]
> 不着急，这个确实要自己的训练的。你已经成功迈出第一步，你可以把这一步替换的步骤细化直接在项目修改 成为项目贡献者 感谢

你应该把文档做的详细些，做到按步骤来就可以跑起来。
接你文档来python synthesizer_preprocess_audio.py <datasets_root>这里就报错了
也不知道哪些步骤是否是必须的
既然选择了开源，其时你也可以提供一些训练好的模型
直接搭好就可以演示start就上来了

**Comment by babysor** [comment]
> > 不着急，这个确实要自己的训练的。你已经成功迈出第一步，你可以把这一步替换的步骤细化直接在项目修改 成为项目贡献者 感谢
> 
> 你应该把文档做的详细些，做到按步骤来就可以跑起来。
> 接你文档来python synthesizer_preprocess_audio.py <datasets_root>这里就报错了
> 也不知道哪些步骤是否是必须的
> 既然选择了开源，其时你也可以提供一些训练好的模型
> 直接搭好就可以演示start就上来了

感谢你的反馈，已经补充使用预训练步骤的描述（源wiki里面英文版描述较为详细）
同时，训练模型有个早期训练后上传的下载Link：https://pan.baidu.com/s/10t3XycWiNIg5dN5E_bMORQ
Code：aid4
